# arc.toml -- Arimo project manifest

[project]
name        = "arc"
version     = "1.0"
description = "Arimo v1 native compiler"
entry       = "Main.arm"
license     = "AGPL-3.0"
readme      = "README.md"
keywords    = []
homepage    = ""
repository  = ""

[[project.authors]]
name  = "Egecan Akincıoglu"
email = "dev@egecanakincioglu.com"

# -- Build --------------------------------------------------------------------

[build]
target = "x86_64-pc-windows-gnu"

[profiles.release]
optimize = true

[profiles.dev]
optimize = false

# -- Stdlib -------------------------------------------------------------------

[stdlib]
include = ["arimo.fs", "arimo.process", "arimo.env"]

# -- Dependencies -------------------------------------------------------------

[dependencies]
# arimo-http = "1.0.0"

[dev-dependencies]
# arimo-test = "0.1.0"

# -- Scripts ------------------------------------------------------------------

[scripts]
# lint = "arc check --strict"
# docs = "arc doc"
